// Generated by generate_salimon_phase0_ship.py; do not edit by hand.
pub const CARGO_ROOM_MIN_METERS: [f64; 3] = [-3.2, 0.24731182795698925, 5.1];
pub const CARGO_ROOM_MAX_METERS: [f64; 3] = [2.2, 2.8064516129032255, 10.6];
// [forward min/max, port min/max]; includes the cabin partition at the passage.
pub(super) const CARGO_WALLS: [[f64; 4]; 5] = [
    [-7.56, 0.4, 4.2, 5.1],
    [2.2, 6.56, 4.2, 5.1],
    [-3.4, -3.2, 5.1, 11.0],
    [2.2, 2.4, 5.1, 11.0],
    [-3.4, 2.4, 10.6, 11.0],
];
