// Generated by generate_salimon_phase0_ship.py; do not edit by hand.
// [forward min/max, up min/max, port min/max] in ship-local meters.
pub(super) const THRUSTER_COLLIDERS: [[f64; 6]; 4] = [
    // COLLIDER_Engine_Port_Body
    [
        -9.8,
        -3.0,
        0.3010752688172043,
        1.8494623655913978,
        5.66,
        8.54,
    ],
    // COLLIDER_Engine_Port_SweptFin
    [
        -7.64,
        -4.3,
        0.6236559139784945,
        2.8494623655913975,
        6.989999999999999,
        7.21,
    ],
    // COLLIDER_Engine_Starboard_Body
    [
        -9.8,
        -3.0,
        0.3010752688172043,
        1.8494623655913978,
        -8.54,
        -5.66,
    ],
    // COLLIDER_Engine_Starboard_SweptFin
    [
        -7.64,
        -4.3,
        0.6236559139784945,
        2.8494623655913975,
        -7.21,
        -6.989999999999999,
    ],
];
