export {
  CRASH_SPEED_METERS_PER_SECOND,
  FULL_ROTATION_RADIANS,
  GRAVITATIONAL_CONSTANT,
  MAX_ENGINE_THRUST_KN,
  MAX_PROPAGATION_STEPS,
  SPACESHIP_MASS_KG,
  TARGET_STEP_SECONDS,
} from '@repo/world';

export const TICK_INTERVAL_MS = 30 * 1_000;
export const SPACESHIP_RADIUS_METERS = 200;
export const SPACESHIP_LAUNCH_CLEARANCE_METERS = 1;
export const THRUSTER_DURABILITY_DRAIN_RATE = 0.01;
